### ISSUE TITLE
Support --amend

### ISSUE THREAD

**Issue by FRidh** [planetscale/ghcommit-action#27]
There are quite some actions out there that create commits. Unfortunately, they are not signed. Adding support for `--amend` should, if I am correct, make it possible to sign commits created by other actions.

Note I do not know whether `ghcommit` supports that.

**Comment by npanuhin** [comment]
I also really need the ability to `amend` a commit (other/custom parameters for the `git commit` would also be nice)

**Comment by joemiller** [comment]
This will depend on whether or not the `createCommitOnBranch` graphql api supports amending existing commits. From a glance at the docs I do not think that's the case. https://docs.github.com/en/graphql/reference/mutations#createcommitonbranch

I also searched that page for `"amend"` and came up with nothing :|

If anyone finds a method for amending I'd be happy to take a look at implementing it in https://github.com/planetscale/ghcommit

This may require a feature request to github's graphql api
