### ISSUE TITLE
Can we add support for Arm?

### ISSUE THREAD

**Issue by NikolayMetchev** [planetscale/ghcommit-action#66]
Would it be possible to run this action on arm runners?
Right now it fails when I try and do so.

**Comment by joemiller** [comment]
@NikolayMetchev Hi! Yes, I actually just added arm64 docker images with the recent refactor to pre-build the runtime docker image - https://github.com/planetscale/ghcommit-action/pull/74

Try version v0.2.0 or newer. Please open a new issue if you run into problems as I have not tested it on an arm64 runner yet
